python_cms/blueprints/auth.py
from flask import Blueprint, redirect, request, url_for
from flask_login import login_user, login_required, logout_user
import json
import requests
from oauthlib.oauth2 import WebApplicationClient
from os import environ
from python_cms.models.user import UserModel

# Oauth Configuration
GOOGLE_CLIENT_ID = environ.get("GOOGLE_CLIENT_ID", None)
GOOGLE_CLIENT_SECRET = environ.get("GOOGLE_CLIENT_SECRET", None)
GOOGLE_DISCOVERY_URL = (
    "https://accounts.google.com/.well-known/openid-configuration")

# OAuth2 client setup
client = WebApplicationClient(GOOGLE_CLIENT_ID)

auth_blueprint = Blueprint("auth", __name__)


@auth_blueprint.route("/login")
def login():
  # Find out what URL to hit for Google login
  google_provider_cfg = requests.get(GOOGLE_DISCOVERY_URL).json()
  authorization_endpoint = google_provider_cfg["authorization_endpoint"]

  # construct the request for Google login and provide
  # scopes that let you retrieve user's profile from Google
  request_uri = client.prepare_request_uri(
      authorization_endpoint,
      redirect_uri=request.host_url + "authorize",
      scope=["openid", "email", "profile"],
  )
  return redirect(request_uri)


@auth_blueprint.route("/authorize")
def authorize():
  # Get authorization code Google sent back to you
  code = request.args.get("code")

  # Find out what URL to hit to get tokens that allow you to ask for
  # things on behalf of a user
  google_provider_cfg = requests.get(GOOGLE_DISCOVERY_URL).json()
  token_endpoint = google_provider_cfg["token_endpoint"]

  # Prepare and send request to get tokens!
  token_url, headers, body = client.prepare_token_request(
      token_endpoint,
      authorization_response=request.url,
      redirect_url=request.base_url,
      code=code,
  )
  # send the request to get the tokens
  token_response = requests.post(
      token_url,
      headers=headers,
      data=body,
      auth=(GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET),
  )

  # Parse the tokens from the response body
  client.parse_request_body_response(json.dumps(token_response.json()))

  # Now that we have tokens let's find and hit the URL
  # from Google that gives the user's profile information,
  # including their Google Profile Image and Email
  userinfo_endpoint = google_provider_cfg["userinfo_endpoint"]
  uri, headers, body = client.add_token(userinfo_endpoint)
  userinfo_response = requests.get(uri, headers=headers, data=body)

  # We want to make sure their email is verified.
  # The user authenticated with Google, authorized our
  # app, and now we've verified their email through Google!
  print(userinfo_response.json())
  if userinfo_response.json().get("email_verified"):
    unique_id = userinfo_response.json()["sub"]
    users_email = userinfo_response.json()["email"]
    picture = userinfo_response.json()["picture"]
    users_name = f'{userinfo_response.json()["family_name"]} {userinfo_response.json()["given_name"]}'
  else:
    return "User email not available or not verified by Google.", 400

  # Create a user in our database with the information provided
  # by Google
  user = UserModel(id=unique_id,
                   name=users_name,
                   email=users_email,
                   picture=picture)

  # Doesn't exist? Add to database
  if not UserModel.get(unique_id):
    user.save()

  # Begin the user session by logging the user in.
  # user should be an instance of your `User` class
  login_user(user)

  # redirect the user back to homepage
  return redirect(url_for("pages.index"))


@auth_blueprint.route("/logout")
@login_required
def logout():
  logout_user()
  return redirect(url_for("pages.index"))

python_cms/blueprints/pages.py
from flask import Blueprint, render_template, request, url_for, send_from_directory
from flask.helpers import flash
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename, redirect
import os
from python_cms.models.post import PostModel
from python_cms.forms.post_form import PostForm
from python_cms.models.category import CategoryModel
import python_cms
import html
from flask_ckeditor import upload_success, upload_fail

import bleach  # https://bleach.readthedocs.io/en/latest/

pages_blueprint = Blueprint("pages", __name__)


@pages_blueprint.route("/")
def index():
  posts = PostModel.get_all()
  return render_template('index.html.j2', posts=posts)


@pages_blueprint.route('/about')
def about():
  return render_template('about.html.j2')

# add post
@pages_blueprint.route("/add", methods=['GET', 'POST'])
@login_required
def create_post():
  form = PostForm()

  form.category.choices = [(1, "Sports"), (2, "Travel"), (3, "Music"), (4, "Food")]

  if request.method == 'POST' and form.validate_on_submit():
    unescaped_body = html.unescape(request.form.get('body'))
    clean_body = bleach.clean(unescaped_body,
                              tags=bleach.sanitizer.ALLOWED_TAGS +
                              ['div', 'br', 'p', 'h1', 'h2', 'img', 'h3'],
                              attributes=['src', 'alt', 'style'])
    title = request.form.get('title')
    body = clean_body
    file = request.files['teaser_image']
    promoted = bool(request.form.get('promoted'))
    if file:
      filename = secure_filename(file.filename)
      file.save(os.path.join(python_cms.ROOT_PATH, 'files_upload', filename))
    else:
      filename = ""

    category = CategoryModel.get(request.form.get('category'))

    post = PostModel(title, body, current_user.get_id(), filename, promoted, category)
    post.save()
    flash(f'Post with title: {title} is created')
    return redirect(url_for('pages.create_post'))

  return render_template('create_post.html.j2', form=form)

# delete post
@pages_blueprint.route("/post/delete/<string:post_id>",
                       methods=['GET', 'POST', 'DEL'])
def del_post(post_id):
  post = PostModel.get(post_id)
  if post.author_id == current_user.get_id():
    flash(f'Post with title: {post.title} deleted')
    PostModel.delete_post(post_id)
    return redirect(url_for("pages.index"))
    

  return (print(f'You are not authorized to delete this content')), 403

#edit post
@pages_blueprint.route("/post/edit/<string:post_id>", methods=['GET', 'POST'])
@login_required

def edit_post(post_id):
  post = PostModel.get(post_id)
  if post.author_id == current_user.get_id():

    form = PostForm(title=post.title, teaser_image=post.teaser_image, body=post.body, promoted=post.promoted, category=post.category_id)
    form.category.choices = [(1, "Sports"), (2, "Travel"), (3, "Music"), (4, "Food")]
    # print(post.teaser_image)
    
    if request.method == 'POST' and form.validate_on_submit():
      unescaped_body = html.unescape(request.form.get('body'))
      clean_body = bleach.clean(unescaped_body,
                                tags=bleach.sanitizer.ALLOWED_TAGS +
                                ['div', 'br', 'p', 'h1', 'h2', 'img', 'h3'],
                                attributes=['src', 'alt', 'style'])
      title = request.form.get('title')
      body = clean_body
      
      file = request.files['teaser_image']
      
      if file:
        filename = secure_filename(file.filename)
        file.save(os.path.join(python_cms.ROOT_PATH, 'files_upload', filename))
      else:
        filename = request.form.get('original_teaser_image')
      
      print(f'filenév: {filename}')
           
      promoted = bool(request.form.get('promoted'))
      category = CategoryModel.get(request.form.get('category'))

      new_post = PostModel(title, body, current_user.get_id(), filename, promoted, category)
      new_post.save()
      
      PostModel.delete_post(post_id)
      
      flash(f'Post with title: {title} changed') 
      return redirect(url_for('pages.index'))
            
      
  else:
    (print(f'You are not authorized to edit this content')), 403 
  return render_template('create_post.html.j2', edit=True, form=form, post_id=post.id, teaser_image=post.teaser_image)
 
    
  

#save uploaded file
@pages_blueprint.route('/files/<path:filename>')
def uploaded_files(filename):
  path = os.path.join(python_cms.ROOT_PATH, 'files_upload')
  return send_from_directory(path, filename)

#get single post
@pages_blueprint.route("/post/<string:post_id>")
@login_required
def single_post(post_id):
  post = PostModel.get(post_id)
  return render_template('post.html.j2', post=post)

#validations during file upload
@pages_blueprint.route('/upload', methods=['POST'])
def upload():
  f = request.files.get('upload')
  # Add more validations here
  extension = f.filename.split('.')[-1].lower()
  if extension not in ['jpg', 'gif', 'png', 'jpeg']:
    return upload_fail(message='Image only!')
  file_name = os.path.join(python_cms.ROOT_PATH, 'files_upload', f.filename)
  f.save(os.path.join(file_name))
  url = url_for('pages.uploaded_files', filename=f.filename)
  return upload_success(url=url)  # return upload_success call

python_cms/templates/about.html.j2
{% extends 'base.html.j2' %}
{% block title %} About {% endblock %}

{% block content %}
<h1>This is the About page</h1>
{% endblock %}

python_cms/templates/base.html.j2
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-icons.min.css" />
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
    {% block headsource %} {% endblock %}
  </head>
  <body>
    <header class="navbar">
      <section class="navbar-section">
        <a href="{{ url_for('pages.index') }}" class="navbar-brand mr-2">Home</a>
        <a href="{{ url_for('pages.about') }}" class="navbar-brand mr-2">About</a>
      </section>
      <section class="navbar-section">
        {% if current_user.is_authenticated %}
         <div class="chip user-menu">
           <img class="avatar avatar-sm" src="{{ current_user.profile_pic }}" alt="">
           {{ current_user.name }}
           <div class="user-submenu">
             <a href="{{ url_for('pages.create_post') }}">Create Post</a>
             <a href="{{ url_for('auth.logout') }}">Log out</a>
           </div>
         </div>
         {% else %}
         <a href="{{ url_for('auth.login') }}" class="btn btn-link">Log In</a>
         {% endif %}
      </section>
    </header>
    <main>
    {% block content %} {% endblock %}
    </main>
    {% block bodysource %} {% endblock %}
  </body>
</html>

python_cms/templates/create_post.html.j2
{% extends 'base.html.j2' %}

{% block headsource %}
 {{ ckeditor.load() }}
{% endblock %}


{% block title %} Home {% endblock %}

{% block content %}
  
  {% if edit is defined and edit == True %}
    <h1>Edit post</h1>
  {% else %}
    <h1>Create post</h1>
  {% endif %}
  
  {% for message in get_flashed_messages()  %}
   <div class="toast toast-success">
       <button class="btn btn-clear float-right"></button>
         {{message}}
   </div>
   {% endfor %}

  {% for field, errors in form.errors.items() %}
    {% for error in errors %}
      <div class="toast toast-error">
          <button class="btn btn-clear float-right"></button>
            {{error}}
      </div>
    {% endfor %}
  {% endfor %}

 {% if edit is defined and edit == True %}
<form action="/post/edit/{{ post_id }}" method="POST" class="form-group" enctype="multipart/form-data">
 {% else %}
<form action="/add" method="POST" class="form-group" enctype="multipart/form-data">
 {% endif %}

 {# protect against csrf https://portswigger.net/web-security/csrf/tokens #}
 {{ form.csrf_token() }}

 <input type="hidden" value="{{ form.teaser_image.data }}" name="original_teaser_image" id="originalTeaserImage">
 
 <label for="title"> {{ form.title.label }}</label>
 {{ form.title(class="form-input", placeholder="title")}}
 <label for="teaser_image"> {{ form.teaser_image.label }}</label>

 {% if edit is defined and edit == True and teaser_image != "" %}
    <div class="card", id="img-and-del-button-container">
      <img src="/files/{{teaser_image}}" class="img-responsive article-image-inner del-butt" alt="">
      <button type="button" class="btn tooltip delete-btn delete-img-btn del-butt" data-tooltip="delete image", id="img-del-button"> Delete </button>
    </div> 
    {{ form.teaser_image(class="form-input hidden", id="teaser-image-input")}}
   


 {% else %}
    {{ form.teaser_image(class="form-input")}}


 {% endif %}

 <label class="form-label">{{ form.category.label }}</label>
 {% for subfield in form.category %}
 <label class="form-radio form-inline">
   {{ subfield }}
   <i class="form-icon"></i> {{ subfield.label.text }}
 </label>
 {% endfor %}

 <label for="body" class="form-label"> {{ form.body.label }}</label>
 {{ form.body(class="form-input", placeholder="your article goes here", id='body')}}
 
 {% if edit is defined and edit == True: %}
    {{ form.submit(class="btn btn-primary input-group-btn float-right", id="createPost", value="Save")}}
 {% else: %}
    {{ form.submit(class="btn btn-primary input-group-btn float-right", id="createPost")}}
 {% endif %}  

  <div class="form-group">
    <label class="form-switch"> 
      <input for= {{ form.promoted }}
      <i class="form-icon"></i> {{ form.promoted.label }}
    </label>
  </div>

 </form>

 {{ ckeditor.config(name='body') }}
 
{% endblock %}


{% block bodysource %}
<script src="{{url_for('static', filename="create_post.js")}}"></script>
{% endblock %}

python_cms/templates/index.html.j2
{% extends 'base.html.j2' %}
{% block title %} Nyitólap {% endblock %}


{% block content %}
  {% if posts|length == 0 %}
    <h1 class="no-posts">We have no posts to show</h1>
  {% endif %}

  {% for message in get_flashed_messages()  %}
   <div class="toast toast-information">
       <button class="btn btn-clear float-right"></button>
         {{message}}
   </div>
  {% endfor %}


<div class="columns">
  {% for post in posts|selectattr("promoted", "equalto", True) %}
    <div class="column col-6 col-md-12">
      <div class="card article-card promoted">
        <div class="card-image">
          {% if post.teaser_image == "" %}
            <img src="{{ url_for('static', filename='default.png') }}" class="img-responsive article-image-inner" alt="">
          {% else %}
          <img src="/files/{{post.teaser_image}}" class="img-responsive article-image-inner" alt="">
          {% endif %}

        </div>
        <div class="card-header">
          <div class="card-title h5">{{ post.title }}</div>
          <span class="label label-rounded"> {{ post.category.name }}</span>
        </div>


        <div class="card-footer">
          <a class="btn btn-primary" href="/post/{{ post.id }}">Read More</a>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

<div class="columns">
  {% for post in posts|selectattr("promoted", "equalto", False) %}
    <div class="column col-6 col-md-12">
      <div class="card article-card">
        <div class="card-image">
          {% if post.teaser_image == "" %}
            <img src="{{ url_for('static', filename='default.png') }}" class="img-responsive article-image-inner" alt="">
          {% else %}
          <img src="/files/{{post.teaser_image}}" class="img-responsive article-image-inner" alt="">
          {% endif %}

        </div>
        <div class="card-header">
          <div class="card-title h5">{{ post.title }}</div>
          <span class="label label-rounded"> {{ post.category.name }}</span>
        </div>
        <div class="card-footer">
          <a class="btn btn-primary" href="/post/{{ post.id }}">Read More</a>
        </div>
      </div>
    </div>
  {% endfor %}
</div>


{% endblock %}

{% block bodysource %}
 <script src="{{url_for('static', filename="index_toast.js")}}"></script>
{% endblock %}

python_cms/templates/post.html.j2
{% extends 'base.html.j2' %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
  {% if post.id is not defined %}
    <h1>Post not found</h1>
  {% else %}
  {% if post.author_id == current_user.get_id() %}
    <button class="btn tooltip delete-btn" data-tooltip="permanently delete this post">
    <a href="/post/delete/{{ post.id }}"> Delete </a>
    </button>
    <button class="btn tooltip edit-btn" data-tooltip="edit this post">
    <a href="/post/edit/{{ post.id }}"> Edit </a>
    </button>   

  {% endif %}
  <h1>{{ post.title }}</h1>
  {% if post.teaser_image == "" %}
    <img src="{{ url_for('static', filename='default.png') }}" class="img-responsive article-image-inner" alt="">
  {% else %}
  <img src="/files/{{post.teaser_image}}" class="img-responsive article-image-inner" alt="">
  {% endif %}
  {{ post.body|safe }}
  {% endif %}
{% endblock %}